# Generated by Django 4.2.15 on 2024-08-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_rating_options_rating_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
