# Generated by Django 4.2.15 on 2024-08-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
