# Generated by Django 4.2.15 on 2024-08-26 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_slider_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='slider',
            name='image_path',
        ),
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, help_text='Upload the slider image', upload_to='slider_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='alt_text',
            field=models.CharField(help_text='Alternative text for the image', max_length=255),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link_url',
            field=models.URLField(blank=True, help_text='URL to redirect when the slider is clicked', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Order of the slider image', null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='status',
            field=models.BooleanField(default=True, help_text='Toggle to activate/deactivate the slider'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle of the slider image', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(help_text='Title of the slider image', max_length=255),
        ),
    ]
